/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nerdzsocialasocials;

import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Ayşe Elif Çelik
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        moodTracker = new javax.swing.JButton();
        diary = new javax.swing.JButton();
        dailyMotivation = new javax.swing.JButton();
        goalAch = new javax.swing.JButton();
        challengeYourself = new javax.swing.JButton();
        mainDesktop = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NERDz - Social Asocials");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/images/Koa.png")).getImage());
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        mainPanel.setBackground(new java.awt.Color(204, 204, 255));

        moodTracker.setBackground(new java.awt.Color(0, 0, 0));
        moodTracker.setFont(new java.awt.Font("MS UI Gothic", 3, 18)); // NOI18N
        moodTracker.setForeground(new java.awt.Color(204, 204, 255));
        moodTracker.setText("Mood Tracker");
        moodTracker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moodTrackerActionPerformed(evt);
            }
        });

        diary.setBackground(new java.awt.Color(0, 0, 0));
        diary.setFont(new java.awt.Font("MS UI Gothic", 3, 18)); // NOI18N
        diary.setForeground(new java.awt.Color(204, 204, 255));
        diary.setText("Diary");
        diary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaryActionPerformed(evt);
            }
        });

        dailyMotivation.setBackground(new java.awt.Color(0, 0, 0));
        dailyMotivation.setFont(new java.awt.Font("MS UI Gothic", 3, 18)); // NOI18N
        dailyMotivation.setForeground(new java.awt.Color(204, 204, 255));
        dailyMotivation.setText("Daily Motivation");
        dailyMotivation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dailyMotivationActionPerformed(evt);
            }
        });

        goalAch.setBackground(new java.awt.Color(0, 0, 0));
        goalAch.setFont(new java.awt.Font("MS UI Gothic", 3, 18)); // NOI18N
        goalAch.setForeground(new java.awt.Color(204, 204, 255));
        goalAch.setText("Goals, Achievements");
        goalAch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goalAchActionPerformed(evt);
            }
        });

        challengeYourself.setBackground(new java.awt.Color(0, 0, 0));
        challengeYourself.setFont(new java.awt.Font("MS UI Gothic", 3, 18)); // NOI18N
        challengeYourself.setForeground(new java.awt.Color(204, 204, 255));
        challengeYourself.setText("Challenge Yourself");
        challengeYourself.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                challengeYourselfActionPerformed(evt);
            }
        });

        mainDesktop.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NERDz");
        jLabel1.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Social Asocials");
        jLabel2.setOpaque(true);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/K.png"))); // NOI18N

        mainDesktop.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        mainDesktop.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        mainDesktop.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout mainDesktopLayout = new javax.swing.GroupLayout(mainDesktop);
        mainDesktop.setLayout(mainDesktopLayout);
        mainDesktopLayout.setHorizontalGroup(
            mainDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainDesktopLayout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addGroup(mainDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        mainDesktopLayout.setVerticalGroup(
            mainDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainDesktopLayout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(moodTracker, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(diary, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(dailyMotivation, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(goalAch, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(challengeYourself, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainDesktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mainDesktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moodTracker, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(diary, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dailyMotivation, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(goalAch, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(challengeYourself, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void moodTrackerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moodTrackerActionPerformed
        MoodTracker mt = new MoodTracker();
        mainDesktop.add(mt);
        mt.setVisible(true);
    }//GEN-LAST:event_moodTrackerActionPerformed

    private void diaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaryActionPerformed
        Diary d = new Diary();
        mainDesktop.add(d);
        d.setDate();
        d.setVisible(true);
    }//GEN-LAST:event_diaryActionPerformed

    private void dailyMotivationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dailyMotivationActionPerformed
        ArrayList<String> quotes = new ArrayList<>();
        quotes.add("\"Every time you are tempted to react in the same old way, ask if you want to be a prisoner of the past or a pioneer of the future.\" -- Deepak Chopra");
        quotes.add("\"You must learn to let go. Release the stress. You were never in control anyway.\"  -- Steve Maraboli");
        quotes.add("\"Difficult roads often lead to beautiful destinations. The best is yet to come.\" -- Zig Ziglar");
        quotes.add("\"If you can't fly then run, if you can't run then walk, if you can't walk then crawl, but whatever you do you have to keep moving forward.\" -- Martin Luther King Jr.");
        quotes.add("\"Just when the caterpillar thought the world was ending, he turned into a butterfly.\" -- Proverb");
        quotes.add("\"If you trade your authenticity for safety, you may experience the following: anxiety, depression, eating disorders, addiction, rage, blame, resentment, and inexplicable grief.\" -- Brené Brown");
        quotes.add("\"If you don't like something change it; if you can't change it, change the way you think about it.\" -- Mary Engelbreit");
        quotes.add("\"Unexpected kindness is the most powerful, least costly, and most underrated agent of human change.\" -- Bob Kerrey");
        quotes.add("\"The way you tell your story to yourself matters.\" -- Amy Cuddy");
        quotes.add("\"When I let go of what I am, I become what I might be.\"-- Lao Tzu");
        quotes.add("\"Worry often gives a small thing a big shadow.\" -- Swedish Proverb");
        quotes.add("\"Act the way that you want to feel.\" -- Gretchen Rubin");
        quotes.add("\"What people in the world think of you is really none of your business.\" -- Martha Graham");
        quotes.add("\"To change ourselves effectively, we first had to change our perceptions.\" -- Stephen R. Covey");
        quotes.add("\"You wouldn't worry so much about what others think of you if you realized how seldom they do.\" -- Eleanor Roosevelt");
        quotes.add("\"Loving people live in a loving world. Hostile people live in a hostile world. Same world.\" -- Wayne W. Dyer");
        quotes.add("\"A positive attitude gives you power over your circumstances instead of your circumstances having power over you.\" -- Joyce Meyer");
        quotes.add("\"The greatest weapon against stress is our ability to choose one thought over another.\" -- William James");
        quotes.add("\"It's not stress that kills us, it is our reaction to it.\" -- Hans Selye");
        quotes.add("\"Don't underestimate the value of Doing Nothing, of just going along, listening to all the things you can't hear, and not bothering.\" -- Winnie the Pooh");
        quotes.add("\"Worry is like a rocking chair: it gives you something to do but never gets you anywhere.\" -- Erma Bombeck");
        quotes.add("\"If you could only sense how important you are to the lives of those you meet; how important you can be to the people you may never even dream of. There is something of yourself that you leave at every meeting with another person.\" -- Fred Rogers");
        quotes.add("\"Nothing can bring you peace but yourself.\" -- Ralph Waldo Emerson");
        Random randomGenerator = new Random();
        int index = randomGenerator.nextInt(quotes.size());
        JOptionPane.showMessageDialog(null, quotes.get(index) + "\nSource: 23 Motivational Quotes to Help You Overcome Anxiety | Inc.com", "Daily Motivation", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_dailyMotivationActionPerformed

    private void goalAchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goalAchActionPerformed
        GoalsAchievements ga = new GoalsAchievements();
        mainDesktop.add(ga);
        ga.setVisible(true);
    }//GEN-LAST:event_goalAchActionPerformed

    private void challengeYourselfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_challengeYourselfActionPerformed
        ArrayList<String> challenge = new ArrayList<>();
        challenge.add("Go outside alone and enjoy!");
        challenge.add("Talk to a stranger.");
        challenge.add("Ask a question to a shop personal.");
        challenge.add("Ask someone you don't know an address.");
        challenge.add("Stop overthinking and watch your favorite movie.");
        challenge.add("Visit your neighbor.");
        challenge.add("Call a restaurant and order something.");
        challenge.add("Tell someone that they are pretty or handsome.");
        
        Random randomGenerator = new Random();
        int index = randomGenerator.nextInt(challenge.size());
        JOptionPane.showMessageDialog(null, challenge.get(index), "New Challenge", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_challengeYourselfActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        JOptionPane.showMessageDialog(null, "Welcome to NERDz! Why don't you start with entering your mood?", "Welcome", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton challengeYourself;
    private javax.swing.JButton dailyMotivation;
    private javax.swing.JButton diary;
    private javax.swing.JButton goalAch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JDesktopPane mainDesktop;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton moodTracker;
    // End of variables declaration//GEN-END:variables
}
